/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CachedRouteImport } from './routes/cached'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SongsPasteRouteImport } from './routes/songs/paste'
import { Route as SongsSongIdRouteImport } from './routes/songs/$songId'

const CachedRoute = CachedRouteImport.update({
  id: '/cached',
  path: '/cached',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsPasteRoute = SongsPasteRouteImport.update({
  id: '/songs/paste',
  path: '/songs/paste',
  getParentRoute: () => rootRouteImport,
} as any)
const SongsSongIdRoute = SongsSongIdRouteImport.update({
  id: '/songs/$songId',
  path: '/songs/$songId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cached': typeof CachedRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/songs/paste': typeof SongsPasteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cached': typeof CachedRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/songs/paste': typeof SongsPasteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cached': typeof CachedRoute
  '/songs/$songId': typeof SongsSongIdRoute
  '/songs/paste': typeof SongsPasteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cached' | '/songs/$songId' | '/songs/paste'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cached' | '/songs/$songId' | '/songs/paste'
  id: '__root__' | '/' | '/cached' | '/songs/$songId' | '/songs/paste'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CachedRoute: typeof CachedRoute
  SongsSongIdRoute: typeof SongsSongIdRoute
  SongsPasteRoute: typeof SongsPasteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/cached': {
      id: '/cached'
      path: '/cached'
      fullPath: '/cached'
      preLoaderRoute: typeof CachedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/paste': {
      id: '/songs/paste'
      path: '/songs/paste'
      fullPath: '/songs/paste'
      preLoaderRoute: typeof SongsPasteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/songs/$songId': {
      id: '/songs/$songId'
      path: '/songs/$songId'
      fullPath: '/songs/$songId'
      preLoaderRoute: typeof SongsSongIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CachedRoute: CachedRoute,
  SongsSongIdRoute: SongsSongIdRoute,
  SongsPasteRoute: SongsPasteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
